version: "1.0"
name: "WelcomeView"
widgets:
    - name: "MyMoney1"
      implementation: "MoneyWidget"
      color: "#fa5a4a"
      position:
        left: 100
        top: 100
        width: 500
        height: 100
    - name: "MyWeather1"
      implementation: "WeatherWidget"
      color: "#f9bd11"
      options:
        city: "Saint-Petersburg"
      position:
        left: 100
        top: 200
        width: 500
        height: 100
    - name: "MyCalendar1"
      implementation: "CalendarWidget"
      color: "#55b697"
      position:
        left: 100
        top: 300
        width: 500
        height: 100
    - name: "MyCalendar2"
      implementation: "CalendarWidget"
      color: "#a06293"
      position:
        left: 100
        top: 400
        width: 500
        height: 100
    - name: "MyCalendar3"
      implementation: "CalendarWidget"
      color: "#f57993"
      position:
        left: 500
        top: 100
        width: 500
        height: 100
    - name: "MyCalendar4"
      implementation: "CalendarWidget"
      color: "#9ec477"
      position:
        left: 500
        top: 200
        width: 500
        height: 100
    - name: "MyCalendar5"
      implementation: "CalendarWidget"
      color: "#9cb3d2"
      position:
        left: 500
        top: 300
        width: 500
        height: 100
    - name: "MyCalendar6"
      implementation: "CalendarWidget"
      color: "#9cd2b3"
      position:
        left: 500
        top: 400
        width: 500
        height: 100


